# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build macOS Installer

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

# Note that the builds produced by this build WILL NOT RUN on macOS Monterey!
# They will be flagged as unsigned and quarantined. You can run a command-line
# to un-quarantine them, but obviously that's not practical for end-users.
# Instead, you will need to set up the signing and notarization to get this to work
# seamlessly for users. See the notes on signing linked to in the README.md
# in the root of this directory.

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17.0.1
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B clean install --file pom.xml
      - name: Update Automatic Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN}}"
          automatic_release_tag: "macOS-latest"
          prerelease: true
          title: "macOS Development Build"
          files: ./target/*.dmg
